parameters:
  rabbit_mq_credentials:
    host: '109.248.59.124'
    user: 'guest'
    pass: 'guest'
    port: '5672'
  telegram_bot:
    token: '863176881:AAHBJ2IUoNAIkxv9fLKpOfQop5eQe9p68gk'
    chat_id: '304165806'